# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  mvn-test-x86:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, [self-hosted, macos, aarch64]]
        java-version: ['8', '11']

    steps:
    - uses: actions/checkout@v2
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v1.4.3
      with:
        java-version: ${{ matrix.java-version }}
    - name: Build with Maven
      run: mvn -B package --file pom.xml

  mvn-test-macos-aarch64:

    runs-on: [self-hosted, macos, aarch64]

    name: mvn test on Apple M1

    steps:
    - uses: actions/checkout@v2
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: 11
        architecture: arm
    - name: Build with Maven
      run: mvn -B package --file pom.xml
